p2p/discover/portal_protocol.go, p2p/discover/portal_protocol_test.go
=> Content look up

p2p/discover/portal_protocol.go, p2p/discover/portal_protocol_test.go, p2p/discover/portalwire/messages.go, portalnetwork/history/history_network.go
=> feat:add gossip content

cmd/hive/main.go, p2p/discover/api.go, p2p/discover/portal_protocol.go, p2p/discover/portal_protocol_test.go, portalnetwork/history/history_network.go, portalnetwork/storage/sqlite/content_storage.go, portalnetwork/storage/sqlite/content_storage_test.go
1. add main entry for portal hive test
2. add some json-rpc method
3. fix bugs in content storage
related #7
=> Portal Hive test

p2p/discover/portalwire/messages_test.go
=> feat:add accept ssz test

p2p/discover/api.go, p2p/discover/portal_protocol.go, p2p/discover/portal_protocol_test.go
add trace content lookup method #21
=> Trace content lookup

p2p/discover/api.go, p2p/discover/portal_protocol.go, p2p/discover/portal_protocol_test.go, portalnetwork/history/api.go, portalnetwork/history/history_network.go
=> feat: change method params

portalnetwork/beacon/storage.go, portalnetwork/beacon/storage_test.go
impl get and put for LightClientFinalityUpdate and LightClientOptimisticUpdate
fixes #76
=> feat: beacon-storage-part2

portalnetwork/beacon/beacon_network.go, portalnetwork/beacon/light_client.go, portalnetwork/beacon/portal_api.go
=> feat:add light client types

portalnetwork/beacon/light_client.go, portalnetwork/beacon/light_client_test.go, portalnetwork/beacon/types.go
1. add apply update fixes #87 
2. add test for verify update
=> Apply update

portalnetwork/beacon/light_client.go, portalnetwork/beacon/light_client_test.go
=> Client sync

portalnetwork/beacon/light_client.go, portalnetwork/state/types.go, portalnetwork/state/types_test.go
=> feat:add state nibbles type

cmd/shisui/main.go, portalnetwork/beacon/types.go, portalnetwork/history/storage.go, portalnetwork/history/storage_test.go
1. change Serialize method
2. refactor history storage
=> refactor: history storage

README.md, cmd/utils/flags.go, p2p/discover/portal_protocol.go
=> fix: panic

cmd/utils/flags.go, go.mod, go.sum, node/defaults.go, p2p/discover/portal_protocol.go
=> fix: cache node id and add logs

portalnetwork/beacon/storage.go, portalnetwork/history/storage.go, portalnetwork/storage/content_storage.go
=> fix: beacon chain tests

portalnetwork/beacon/beacon_network.go, portalnetwork/beacon/beacon_network_test.go, portalnetwork/beacon/test_utils.go
=> feat: add history proof validation test

cmd/shisui/main.go, portalnetwork/history/storage.go, portalnetwork/history/storage_test.go, portalnetwork/state/api.go, portalnetwork/state/network.go, portalnetwork/storage/config.go
=> feat: add state api

portalnetwork/state/network.go, portalnetwork/state/network_test.go, trie/portal.go
=> feat: add validation for contract storage and contract bytecode

Makefile
=> Make sure that the build/bin directory exists to copy the executable

portalnetwork/state/storage.go, portalnetwork/state/storage_test.go
=> fix: state storage err

p2p/discover/api.go, portalnetwork/history/storage.go
=> fix: offer test failed in hive state interop

p2p/discover/portal_protocol.go
=> Replace log trace strings to easily readable

p2p/discover/v5wire/encoding.go
=> fix:make only sent whoareyou challenges first time

cmd/shisui/main.go
=> fix: write key error

p2p/discover/portal_protocol.go, p2p/discover/v5_udp.go
Reverts optimism-java/shisui#193
=> Revert "fix: utp send call to maintain nonce"

p2p/discover/portal_protocol.go
Implements #191 
Add message: "Node added to bucket"
=> Add message of new node added to bucket

cmd/shisui/main.go, cmd/utils/flags.go
=> Add flag to format logs

portalnetwork/beacon/api.go, portalnetwork/history/api.go, portalnetwork/history/history_network.go, portalnetwork/state/api.go
=> feat: rpc api change

portalnetwork/state/network.go, portalnetwork/state/network_test.go
=> fix: rpc method error in state network

cmd/shisui/main.go, metrics/portal_metrics.go, portalnetwork/beacon/storage.go, portalnetwork/history/storage.go, portalnetwork/state/storage.go, portalnetwork/state/storage_test.go
Implementation/fix of the following metrics:
portal/\<NETWORK\>/radius_ratio
portal/\<NETWORK\>/entry_count
portal/\<NETWORK\>/content_storage
portal/\<NETWORK\>/total_storage
=> Metrics implementation

portalnetwork/storage/content_storage.go, portalnetwork/storage/ethpepple/storage.go, portalnetwork/storage/ethpepple/storage_test.go
part1: impl simple get and put method
=> feat: use ethdb to store data

p2p/discover/api.go, p2p/discover/portal_protocol.go, portalnetwork/beacon/api.go, portalnetwork/history/api.go, portalnetwork/state/api.go
=> add PutContent
